"""order table

Revision ID: af987c9246c1
Revises: 97dfd81294d6
Create Date: 2018-04-22 16:13:35.895530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af987c9246c1'
down_revision = '97dfd81294d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('carrier', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('cont', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('dueDate', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('etaDate', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('po', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'po')
    op.drop_column('order', 'name')
    op.drop_column('order', 'etaDate')
    op.drop_column('order', 'dueDate')
    op.drop_column('order', 'cont')
    op.drop_column('order', 'carrier')
    # ### end Alembic commands ###
